coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
        base: auto
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
        
  ignore:
    - "static-web-app/coverage/**/*"
    - "static-web-app/__tests__/**/*" 
    - "static-web-app/jest.config.js"
    - "static-web-app/jest.setup.js"
    - "static-web-app/jest.setup.d.ts"
    - "static-web-app/*.config.*"
    - "static-web-app/globals.css"
    - "static-web-app/app/globals.css"
    
comment:
  layout: "header,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - static-web-app/
    carryforward: true