blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/KennethHeine/kennethheine.com/discussions
    about: Ask questions, share ideas, or discuss improvements
  - name: 🔒 Security Issue
    url: https://github.com/KennethHeine/kennethheine.com/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📧 Direct Contact
    url: https://kennethheine.com/contact
    about: Contact Kenneth directly through the website