name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      contents: read

    steps:
      # 🏗️ Environment Setup
      - name: "🔍 Checkout repository"
        uses: actions/checkout@v4

      # 📦 Node.js Setup for Frontend Development
      - name: "⚡ Setup Node.js 22"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "static-web-app/package-lock.json"      

      - name: "📦 Install JavaScript dependencies"
        working-directory: ./static-web-app
        run: |
          npm ci
          echo "✅ Node.js dependencies installed successfully"
