name: Deploy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  DEPLOYMENT_LOCATION: "westeurope"

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Files
        run: |
          echo "Listing files in infra/parameters:"
          ls -la infra/parameters

      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure CLI and Authentication
        run: |
          echo "🔍 Verifying Azure CLI setup..."
          az version
          az account show
          echo "✅ Authentication verified"

      - name: Deploy Infrastructure
        run: |
          deployment_name="kennethheine-deploy-$(date +%Y%m%d%H%M%S)"
          
          echo "🚀 Deploying infrastructure..."
          echo "📍 Deployment Name: $deployment_name"
          echo "🌍 Location: ${{ env.DEPLOYMENT_LOCATION }}"
          
          # Check if files exist
          if [ ! -f "infra/main.bicep" ]; then
            echo "❌ main.bicep file not found"
            exit 1
          fi
          
          if [ ! -f "infra/parameters/production.bicepparam" ]; then
            echo "❌ production.bicepparam file not found"
            exit 1
          fi
          
          echo "📁 Files verified, starting deployment..."
          
          az deployment sub create \
            --name "$deployment_name" \
            --location "${{ env.DEPLOYMENT_LOCATION }}" \
            --template-file "infra/main.bicep" \
            --parameters "infra/parameters/production.bicepparam" \
            --verbose

          echo "✅ Infrastructure deployment completed!"