# Deploy Infrastructure to Azure
# Simple workflow to deploy Bicep infrastructure

name: Deploy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  DEPLOYMENT_LOCATION: "westeurope"

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure
        run: |
          deployment_name="kennethheine-deploy-$(date +%Y%m%d%H%M%S)"
          
          echo "🚀 Deploying infrastructure..."
          echo "📍 Deployment Name: $deployment_name"
          echo "🌍 Location: ${{ env.DEPLOYMENT_LOCATION }}"
          
          az deployment sub create \
            --name "$deployment_name" \
            --location "${{ env.DEPLOYMENT_LOCATION }}" \
            --template-file "infra/main.bicep" \
            --parameters "infra/parameters/production.bicepparam"
          
          echo "✅ Infrastructure deployment completed!"
